import type { AppLanguage } from "./language";

export function getLanguageLocale(language: AppLanguage) {
  if (language === "fr") {
    return "fr-FR";
  }

  return "en-US";
}

export function getStatusLabel(language: AppLanguage, status: string) {
  const normalized = status.toLowerCase();

  if (normalized === "completed") {
    return language === "fr" ? "termine" : language === "cr" ? "termine" : "completed";
  }

  if (normalized === "pending") {
    return language === "fr" ? "en attente" : language === "cr" ? "an atant" : "pending";
  }

  if (normalized === "failed") {
    return language === "fr" ? "echec" : language === "cr" ? "fini ar erer" : "failed";
  }

  return status;
}

const copy = {
  en: {
    layout: {
      portal: "User Portal",
      access: "Personal Access",
      dashboard: "Dashboard",
      wallet: "Wallet",
      creditsWallet: "Credits Wallet",
      transfer: "Transfer",
      bill: "Bill",
      settlement: "Settlement",
      history: "History",
      settings: "Settings",
      signOut: "Sign out",
      logoutSuccess: "Logout successful.",
      userFallback: "SoleyVolt User",
      consumerSubtitle: "Track bill obligations, imported energy, and Green Coin bill reduction options.",
      producerSubtitle: "Monitor exported energy, Yellow Coin rewards, and stored production credits.",
      prosumerSubtitle: "Manage both consumption and production with one complete energy wallet view.",
      consumerTitle: "Consumption and bill management",
      producerTitle: "Production credits and earnings",
      prosumerTitle: "Balanced consumption and production",
    },
    dashboard: {
      loadError: "Unable to load dashboard data.",
      onboarding:
        "Your account is ready. Energy charts and monthly calculations will appear after an admin links your profile to imported dataset rows or after your first energy readings are recorded.",
      importedEnergy: "Imported Energy",
      exportedEnergy: "Exported Energy",
      redCoins: "Red Coins",
      billEstimate: "Bill Estimate",
      yellowCoinsEarned: "Yellow Coins Earned",
      walletBalance: "Wallet Balance",
      netEnergy: "Net Energy",
      latestImport: "latest import",
      noReadingsYet: "No readings yet",
      consumptionLinked: "Consumption-linked bill obligation",
      greenCoinReduction: "Green Coin reduction",
      latestReward: "latest reward",
      storedCredits: "Stored credits",
      lifetimeEarned: "Lifetime earned",
      consumptionPressure: "Consumption pressure",
      yellowCoins: "Yellow Coins",
      chartConsumer: "Consumption trend",
      chartProducer: "Production trend",
      chartProsumer: "Import vs export balance",
      summaryConsumer: "Bill reduction summary",
      summaryProducer: "Stored production credits",
      summaryProsumer: "Net energy and coin summary",
      loadingReadings: "Loading energy readings...",
      noReadings: "No energy readings yet. Add readings in Supabase to see your live chart.",
      importedEnergyLine: "Import (kWh)",
      exportedEnergyLine: "Export (kWh)",
      importedEnergyLabel: "Imported energy",
      exportedEnergyLabel: "Exported energy",
      greenCoinOption: "Green Coin option",
      estimatedNetObligation: "Estimated net obligation",
      guidanceProducer: "Producer guidance",
      guidanceConsumer: "Consumer guidance",
      guidanceProsumer: "Prosumer guidance",
      guidanceProducerA: "Production rewards are highlighted first so you can track surplus export performance.",
      guidanceProducerB: "Bill-oriented consumption widgets are intentionally de-emphasized here.",
      guidanceConsumerA: "Your dashboard focuses on imported energy, Red Coin obligation, and bill reduction tools.",
      guidanceConsumerB: "Production charts are minimized because they are not central to a consumer flow.",
      guidanceProsumerA: "Your dashboard balances both sides of the energy profile so you can see obligation and rewards together.",
      guidanceProsumerB: "This is the fullest portal mode, combining billing, credits, and net energy position.",
      activityProducer: "Production and wallet activity",
      activityDefault: "Transaction and activity history",
      liveBackendData: "Live backend data",
      incomingTransfer: "Incoming transfer",
      outgoingTransfer: "Outgoing transfer",
      solarReward: "Solar production reward",
      loadingTransactions: "Loading transactions...",
      noTransactions: "No transactions yet.",
    },
    wallet: {
      loadError: "Unable to load wallet data.",
      storedCredits: "Stored Credits",
      billOffsetWallet: "Bill Offset Wallet",
      hybridWallet: "Hybrid Energy Wallet",
      loading: "Loading...",
      storedProductionCredits: "Stored production credits",
      availableBillOffset: "Available bill-offset balance",
      combinedSettlementBalance: "Combined settlement balance",
      earned: "Earned",
      spent: "Spent",
      transactionHistory: "Transaction History",
      liveBackendData: "Live backend data",
      type: "Type",
      description: "Description",
      date: "Date",
      time: "Time",
      amount: "Amount",
      status: "Status",
      loadingTransactions: "Loading transactions...",
      noWalletActivity: "No wallet activity yet.",
    },
    bill: {
      titleProducer: "Settlement and credit position",
      titleDefault: "Bill and offset summary",
      descProducer: "Review production-led credits, expected settlement value, and how your stored earnings are accumulating.",
      descDefault: "Track current bill obligation, Red Coin exposure, and how Green or Yellow Coin activity helps reduce payable energy costs.",
      invalidGreenCoinAmount: "Enter a valid Green Coin amount.",
      purchaseSuccess: "Purchased {amount} Green Coins.",
      purchaseError: "Unable to purchase Green Coins.",
      loadError: "Unable to load bill data.",
      importedEnergy: "Imported energy",
      redCoins: "Red Coins",
      greenCoins: "Green Coins",
      settlementEstimate: "Settlement estimate",
      billEstimate: "Bill estimate",
      buyGreenCoins: "Buy Green Coins",
      currentLiveUnitPrice: "Current live unit price",
      purchaseAmount: "Purchase amount",
      processing: "Processing...",
      buyAction: "Buy Green Coins",
      currentPosition: "Current position",
      exportedEnergy: "Exported energy",
      yellowCoinSupport: "Yellow Coin support",
      estimatedNetObligation: "Estimated net obligation",
      recentPurchases: "Recent Green Coin purchases",
      loadingPurchases: "Loading purchases...",
      noPurchases: "No Green Coin purchases yet.",
      gcPurchased: "GC purchased",
      marketPhase: {
        night: "Night demand",
        morning: "Morning cooldown",
        day: "Midday balance",
        evening: "Evening ramp",
      },
    },
    settings: {
      loadError: "Unable to load settings.",
      profileUpdated: "Profile updated successfully.",
      profileSaveError: "Unable to save profile.",
      preferencesSaved: "Preferences saved successfully.",
      preferencesSaveError: "Unable to save preferences.",
      passwordRequired: "Enter a new password.",
      passwordMismatch: "New password and confirmation do not match.",
      passwordUpdated: "Password updated successfully.",
      passwordUpdateError: "Unable to update password.",
      profileInformation: "Profile Information",
      currentUserType: "Current user type",
      fullName: "Full Name",
      email: "Email",
      phoneNumber: "Phone Number",
      saveChanges: "Save Changes",
      security: "Security",
      changePassword: "Change Password",
      newPassword: "New Password",
      confirmNewPassword: "Confirm New Password",
      enterNewPassword: "Enter a new password",
      reenterPassword: "Re-enter your new password",
      updating: "Updating...",
      updatePassword: "Update Password",
      twoFactor: "Two-Factor Authentication",
      twoFactorDesc: "Store your MFA preference in the backend settings record",
      languagePreferences: "Language Preferences",
      selectLanguage: "Select Language",
      notifications: "Notifications",
      emailNotifications: "Email Notifications",
      emailNotificationsDesc: "Receive updates via email",
      pushNotifications: "Push Notifications",
      pushNotificationsDesc: "Receive push notifications on your device",
      transactionAlerts: "Transaction Alerts",
      transactionAlertsDesc: "Get notified for all transactions",
      savePreferences: "Save Preferences",
      saving: "Saving...",
      english: "English",
      french: "Francais",
      kreol: "Kreol",
    },
    history: {
      loadError: "Unable to load transaction history.",
      title: "Transaction history",
      description:
        "Review every wallet movement tied to your account, including solar rewards, incoming transfers, and tokens you sent.",
      type: "Type",
      detail: "Description",
      counterparty: "Counterparty",
      timestamp: "Timestamp",
      amount: "Amount",
      status: "Status",
      noDescription: "No description",
      system: "System",
      loading: "Loading transaction history...",
      empty: "No transaction history is available yet.",
    },
  },
  fr: {
    layout: {
      portal: "Portail utilisateur",
      access: "Acces personnel",
      dashboard: "Tableau de bord",
      wallet: "Portefeuille",
      creditsWallet: "Portefeuille credits",
      transfer: "Transferer",
      bill: "Facture",
      settlement: "Reglement",
      history: "Historique",
      settings: "Parametres",
      signOut: "Se deconnecter",
      logoutSuccess: "Deconnexion reussie.",
      userFallback: "Utilisateur SoleyVolt",
      consumerSubtitle: "Suivez les obligations de facture, l'energie importee et les options de reduction avec Green Coin.",
      producerSubtitle: "Surveillez l'energie exportee, les recompenses Yellow Coin et les credits de production stockes.",
      prosumerSubtitle: "Gerez consommation et production avec une vue complete du portefeuille energie.",
      consumerTitle: "Consommation et gestion de facture",
      producerTitle: "Credits de production et gains",
      prosumerTitle: "Consommation et production equilibrees",
    },
    dashboard: {
      loadError: "Impossible de charger les donnees du tableau de bord.",
      onboarding:
        "Votre compte est pret. Les graphiques energie et calculs mensuels apparaitront apres le lien admin avec les donnees importees ou apres vos premiers releves.",
      importedEnergy: "Energie importee",
      exportedEnergy: "Energie exportee",
      redCoins: "Red Coins",
      billEstimate: "Estimation de facture",
      yellowCoinsEarned: "Yellow Coins gagnes",
      walletBalance: "Solde du portefeuille",
      netEnergy: "Energie nette",
      latestImport: "dernier import",
      noReadingsYet: "Aucun releve pour le moment",
      consumptionLinked: "Obligation liee a la consommation",
      greenCoinReduction: "Reduction Green Coin",
      latestReward: "derniere recompense",
      storedCredits: "Credits stockes",
      lifetimeEarned: "Gain cumule",
      consumptionPressure: "Pression de consommation",
      yellowCoins: "Yellow Coins",
      chartConsumer: "Tendance de consommation",
      chartProducer: "Tendance de production",
      chartProsumer: "Equilibre import / export",
      summaryConsumer: "Resume de reduction de facture",
      summaryProducer: "Credits de production stockes",
      summaryProsumer: "Resume energie nette et coins",
      loadingReadings: "Chargement des releves energie...",
      noReadings: "Aucun releve energie pour le moment. Ajoutez des releves dans Supabase pour voir le graphique.",
      importedEnergyLine: "Import (kWh)",
      exportedEnergyLine: "Export (kWh)",
      importedEnergyLabel: "Energie importee",
      exportedEnergyLabel: "Energie exportee",
      greenCoinOption: "Option Green Coin",
      estimatedNetObligation: "Obligation nette estimee",
      guidanceProducer: "Guide producteur",
      guidanceConsumer: "Guide consommateur",
      guidanceProsumer: "Guide prosumer",
      guidanceProducerA: "Les recompenses de production sont mises en avant pour suivre les surplus exportes.",
      guidanceProducerB: "Les widgets de consommation et de facture sont volontairement moins visibles ici.",
      guidanceConsumerA: "Votre tableau de bord met l'accent sur l'energie importee, les Red Coins et la reduction de facture.",
      guidanceConsumerB: "Les graphiques de production sont minimises car ils ne sont pas centraux pour un consommateur.",
      guidanceProsumerA: "Votre tableau de bord equilibre les deux cotes de votre profil energie pour voir obligations et recompenses ensemble.",
      guidanceProsumerB: "C'est le mode portail le plus complet, avec facturation, credits et position energie nette.",
      activityProducer: "Activite production et portefeuille",
      activityDefault: "Historique des transactions et activites",
      liveBackendData: "Donnees backend en direct",
      incomingTransfer: "Transfert entrant",
      outgoingTransfer: "Transfert sortant",
      solarReward: "Recompense de production solaire",
      loadingTransactions: "Chargement des transactions...",
      noTransactions: "Aucune transaction pour le moment.",
    },
    wallet: {
      loadError: "Impossible de charger le portefeuille.",
      storedCredits: "Credits stockes",
      billOffsetWallet: "Portefeuille de compensation facture",
      hybridWallet: "Portefeuille energie hybride",
      loading: "Chargement...",
      storedProductionCredits: "Credits de production stockes",
      availableBillOffset: "Solde disponible pour reduire la facture",
      combinedSettlementBalance: "Solde combine de reglement",
      earned: "Gagne",
      spent: "Depense",
      transactionHistory: "Historique des transactions",
      liveBackendData: "Donnees backend en direct",
      type: "Type",
      description: "Description",
      date: "Date",
      time: "Heure",
      amount: "Montant",
      status: "Statut",
      loadingTransactions: "Chargement des transactions...",
      noWalletActivity: "Aucune activite de portefeuille pour le moment.",
    },
    bill: {
      titleProducer: "Reglement et position de credits",
      titleDefault: "Resume facture et compensation",
      descProducer: "Consultez les credits issus de la production, la valeur de reglement attendue et l'accumulation de vos gains.",
      descDefault: "Suivez l'obligation actuelle, l'exposition Red Coin et l'effet des Green et Yellow Coins sur la facture.",
      invalidGreenCoinAmount: "Entrez un montant Green Coin valide.",
      purchaseSuccess: "{amount} Green Coins achetes.",
      purchaseError: "Impossible d'acheter des Green Coins.",
      loadError: "Impossible de charger les donnees de facture.",
      importedEnergy: "Energie importee",
      redCoins: "Red Coins",
      greenCoins: "Green Coins",
      settlementEstimate: "Estimation de reglement",
      billEstimate: "Estimation de facture",
      buyGreenCoins: "Acheter des Green Coins",
      currentLiveUnitPrice: "Prix unitaire en direct",
      purchaseAmount: "Quantite a acheter",
      processing: "Traitement...",
      buyAction: "Acheter des Green Coins",
      currentPosition: "Position actuelle",
      exportedEnergy: "Energie exportee",
      yellowCoinSupport: "Soutien Yellow Coin",
      estimatedNetObligation: "Obligation nette estimee",
      recentPurchases: "Achats recents de Green Coins",
      loadingPurchases: "Chargement des achats...",
      noPurchases: "Aucun achat de Green Coin pour le moment.",
      gcPurchased: "GC achetes",
      marketPhase: {
        night: "Demande nocturne",
        morning: "Baisse du matin",
        day: "Equilibre de journee",
        evening: "Hausse du soir",
      },
    },
    settings: {
      loadError: "Impossible de charger les parametres.",
      profileUpdated: "Profil mis a jour avec succes.",
      profileSaveError: "Impossible d'enregistrer le profil.",
      preferencesSaved: "Preferences enregistrees avec succes.",
      preferencesSaveError: "Impossible d'enregistrer les preferences.",
      passwordRequired: "Entrez un nouveau mot de passe.",
      passwordMismatch: "Le nouveau mot de passe et sa confirmation ne correspondent pas.",
      passwordUpdated: "Mot de passe mis a jour avec succes.",
      passwordUpdateError: "Impossible de mettre a jour le mot de passe.",
      profileInformation: "Informations du profil",
      currentUserType: "Type d'utilisateur actuel",
      fullName: "Nom complet",
      email: "Email",
      phoneNumber: "Numero de telephone",
      saveChanges: "Enregistrer",
      security: "Securite",
      changePassword: "Changer le mot de passe",
      newPassword: "Nouveau mot de passe",
      confirmNewPassword: "Confirmer le nouveau mot de passe",
      enterNewPassword: "Entrez un nouveau mot de passe",
      reenterPassword: "Saisissez a nouveau votre mot de passe",
      updating: "Mise a jour...",
      updatePassword: "Mettre a jour le mot de passe",
      twoFactor: "Authentification a deux facteurs",
      twoFactorDesc: "Stockez votre preference MFA dans l'enregistrement backend",
      languagePreferences: "Preferences de langue",
      selectLanguage: "Choisir la langue",
      notifications: "Notifications",
      emailNotifications: "Notifications email",
      emailNotificationsDesc: "Recevoir des mises a jour par email",
      pushNotifications: "Notifications push",
      pushNotificationsDesc: "Recevoir des notifications sur votre appareil",
      transactionAlerts: "Alertes de transaction",
      transactionAlertsDesc: "Recevoir une alerte pour chaque transaction",
      savePreferences: "Enregistrer les preferences",
      saving: "Enregistrement...",
      english: "English",
      french: "Francais",
      kreol: "Kreol",
    },
    history: {
      loadError: "Impossible de charger l'historique des transactions.",
      title: "Historique des transactions",
      description:
        "Consultez tous les mouvements de portefeuille lies a votre compte, y compris les recompenses solaires et les transferts entrants ou sortants.",
      type: "Type",
      detail: "Description",
      counterparty: "Contrepartie",
      timestamp: "Horodatage",
      amount: "Montant",
      status: "Statut",
      noDescription: "Aucune description",
      system: "Systeme",
      loading: "Chargement de l'historique...",
      empty: "Aucun historique disponible pour le moment.",
    },
  },
  cr: {
    layout: {
      portal: "Portal user",
      access: "Akses personel",
      dashboard: "Dashboard",
      wallet: "Wallet",
      creditsWallet: "Wallet kredi",
      transfer: "Transfer",
      bill: "Bil",
      settlement: "Reglman",
      history: "Listwar",
      settings: "Setting",
      signOut: "Sign out",
      logoutSuccess: "Logout reisi.",
      userFallback: "User SoleyVolt",
      consumerSubtitle: "Swiv to lobligasion bil, lenerzi importe, ek opsion rediksion Green Coin.",
      producerSubtitle: "Sivey lenerzi exporte, rekonpans Yellow Coin, ek kredi prodiksion ki finn garde.",
      prosumerSubtitle: "Zer konsomasion ek prodiksion ansam avek enn view wallet lenerzi konplet.",
      consumerTitle: "Konsomasion ek zestion bil",
      producerTitle: "Kredi prodiksion ek reveni",
      prosumerTitle: "Konsomasion ek prodiksion an balans",
    },
    dashboard: {
      loadError: "Pa finn kapav sarz done dashboard.",
      onboarding:
        "To kont pare. Chart lenerzi ek kalkil mansiel pou paret apre ki enn admin link to profil ar bann done importe ouswa apre to premie reading.",
      importedEnergy: "Lenerzi importe",
      exportedEnergy: "Lenerzi exporte",
      redCoins: "Red Coins",
      billEstimate: "Estimasion bil",
      yellowCoinsEarned: "Yellow Coins gagne",
      walletBalance: "Balans wallet",
      netEnergy: "Lenerzi net",
      latestImport: "dernie import",
      noReadingsYet: "Pa ena reading ankor",
      consumptionLinked: "Lobligasion lie ar konsomasion",
      greenCoinReduction: "Rediksion Green Coin",
      latestReward: "dernie rekonpans",
      storedCredits: "Kredi garde",
      lifetimeEarned: "Total gagne",
      consumptionPressure: "Presion konsomasion",
      yellowCoins: "Yellow Coins",
      chartConsumer: "Tandans konsomasion",
      chartProducer: "Tandans prodiksion",
      chartProsumer: "Balans import ek export",
      summaryConsumer: "Rezime rediksion bil",
      summaryProducer: "Kredi prodiksion garde",
      summaryProsumer: "Rezime lenerzi net ek coin",
      loadingReadings: "Pe sarz reading lenerzi...",
      noReadings: "Pa ena reading lenerzi ankor. Azout reading dan Supabase pou trouv chart.",
      importedEnergyLine: "Import (kWh)",
      exportedEnergyLine: "Export (kWh)",
      importedEnergyLabel: "Lenerzi importe",
      exportedEnergyLabel: "Lenerzi exporte",
      greenCoinOption: "Opsion Green Coin",
      estimatedNetObligation: "Lobligasion net estime",
      guidanceProducer: "Gid prodikter",
      guidanceConsumer: "Gid konsomater",
      guidanceProsumer: "Gid prosumer",
      guidanceProducerA: "Rekonpans prodiksion vinn avan pou to kapav swiv surplus exporte.",
      guidanceProducerB: "Widget konsomasion ek bil finn diminie isi.",
      guidanceConsumerA: "To dashboard met latansion lor lenerzi importe, Red Coin, ek zouti rediksion bil.",
      guidanceConsumerB: "Chart prodiksion finn minimize parski li pa keksoz prinsipal pou enn konsomater.",
      guidanceProsumerA: "To dashboard balans toulede kote to profil lenerzi pou trouv lobligasion ek rekonpans ansam.",
      guidanceProsumerB: "Sa mode portal la pli konplet, avek bil, kredi, ek pozision lenerzi net.",
      activityProducer: "Aktivite prodiksion ek wallet",
      activityDefault: "Listwar tranzaksion ek aktivite",
      liveBackendData: "Done backend live",
      incomingTransfer: "Transfer rantre",
      outgoingTransfer: "Transfer sorti",
      solarReward: "Rekonpans prodiksion soler",
      loadingTransactions: "Pe sarz tranzaksion...",
      noTransactions: "Pa ena tranzaksion ankor.",
    },
    wallet: {
      loadError: "Pa finn kapav sarz wallet.",
      storedCredits: "Kredi garde",
      billOffsetWallet: "Wallet rediksion bil",
      hybridWallet: "Wallet lenerzi hybrid",
      loading: "Pe sarz...",
      storedProductionCredits: "Kredi prodiksion garde",
      availableBillOffset: "Balans disponib pou redwir bil",
      combinedSettlementBalance: "Balans reglman konbine",
      earned: "Gagne",
      spent: "Depanse",
      transactionHistory: "Listwar tranzaksion",
      liveBackendData: "Done backend live",
      type: "Tip",
      description: "Deskripsion",
      date: "Dat",
      time: "Ler",
      amount: "Montan",
      status: "Stati",
      loadingTransactions: "Pe sarz tranzaksion...",
      noWalletActivity: "Pa ena aktivite wallet ankor.",
    },
    bill: {
      titleProducer: "Reglman ek pozision kredi",
      titleDefault: "Rezime bil ek offset",
      descProducer: "Get kredi prodiksion, valer reglman ki atann, ek kouma to reveni pe akimile.",
      descDefault: "Swiv lobligasion bil aktyel, expozision Red Coin, ek kouma Green ek Yellow Coins pe ed redwir kout.",
      invalidGreenCoinAmount: "Met enn kantite Green Coin valab.",
      purchaseSuccess: "Finn aste {amount} Green Coins.",
      purchaseError: "Pa finn kapav aste Green Coins.",
      loadError: "Pa finn kapav sarz done bil.",
      importedEnergy: "Lenerzi importe",
      redCoins: "Red Coins",
      greenCoins: "Green Coins",
      settlementEstimate: "Estimasion reglman",
      billEstimate: "Estimasion bil",
      buyGreenCoins: "Aste Green Coins",
      currentLiveUnitPrice: "Pri unit live",
      purchaseAmount: "Kantite aste",
      processing: "Pe travay...",
      buyAction: "Aste Green Coins",
      currentPosition: "Pozision aktyel",
      exportedEnergy: "Lenerzi exporte",
      yellowCoinSupport: "Sipor Yellow Coin",
      estimatedNetObligation: "Lobligasion net estime",
      recentPurchases: "Dernié aste Green Coin",
      loadingPurchases: "Pe sarz aste...",
      noPurchases: "Pa ena aste Green Coin ankor.",
      gcPurchased: "GC aste",
      marketPhase: {
        night: "Demann aswar",
        morning: "Bese gramatin",
        day: "Balans lazourne",
        evening: "Monte aswar",
      },
    },
    settings: {
      loadError: "Pa finn kapav sarz setting.",
      profileUpdated: "Profil finn met azour.",
      profileSaveError: "Pa finn kapav sauvegard profil.",
      preferencesSaved: "Preferans finn sauvegarde.",
      preferencesSaveError: "Pa finn kapav sauvegard preferans.",
      passwordRequired: "Met enn nouvo password.",
      passwordMismatch: "Nouvo password ek konfirmasion pa pe koresponn.",
      passwordUpdated: "Password finn met azour.",
      passwordUpdateError: "Pa finn kapav met azour password.",
      profileInformation: "Informasion profil",
      currentUserType: "Tip user aktyel",
      fullName: "Nom konplet",
      email: "Email",
      phoneNumber: "Numéro telefonn",
      saveChanges: "Sov sanzman",
      security: "Sekirite",
      changePassword: "Sanz password",
      newPassword: "Nouvo password",
      confirmNewPassword: "Konfirm nouvo password",
      enterNewPassword: "Met enn nouvo password",
      reenterPassword: "Retap nouvo password",
      updating: "Pe met azour...",
      updatePassword: "Met azour password",
      twoFactor: "Otantifikasion de-fakter",
      twoFactorDesc: "Gard preferans MFA dan backend",
      languagePreferences: "Preferans langaz",
      selectLanguage: "Swazir langaz",
      notifications: "Notifikasion",
      emailNotifications: "Notifikasion email",
      emailNotificationsDesc: "Resevwar mizazour par email",
      pushNotifications: "Notifikasion push",
      pushNotificationsDesc: "Resevwar notifikasion lor to appareil",
      transactionAlerts: "Lalert tranzaksion",
      transactionAlertsDesc: "Gagn lalert pou sak tranzaksion",
      savePreferences: "Sov preferans",
      saving: "Pe sov...",
      english: "English",
      french: "Francais",
      kreol: "Kreol",
    },
    history: {
      loadError: "Pa finn kapav sarz listwar tranzaksion.",
      title: "Listwar tranzaksion",
      description:
        "Get tou mouvman wallet ki lie ar to kont, inklir rekonpans soler, transfer rantre, ek token ki to finn anvoye.",
      type: "Tip",
      detail: "Deskripsion",
      counterparty: "Kontparti",
      timestamp: "Ler",
      amount: "Montan",
      status: "Stati",
      noDescription: "Pena deskripsion",
      system: "Sistem",
      loading: "Pe sarz listwar tranzaksion...",
      empty: "Pena listwar tranzaksion ankor.",
    },
  },
} as const;

export function getUserPortalCopy(language: AppLanguage) {
  return copy[language];
}
